In [1]:
import numpy as np

## Section 1: np.array()

In [5]:

#create 1d numpy array from list
array1 = np.array([1,2,3,4,5,6])
print(array1)
print(type(array1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [6]:
array2 = np.array([[1,2,3,4],[5,6,7,8]])
print(array2)
print(type(array2))

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


## Section 2: np.zeros/ones/empty/random()

In [ ]:
array3 = np.zeros((3,3))
array3

In [18]:
array3 = np.zeros((5,5))
                
print (array3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# ONES ()

#array5 = np.ones((5))
#print(array5)

#array6 = np.ones((2,3))
#print(array6)

array7 = np.ones((2,2,3))
print(array7)

In [ ]:
# EMPTY()

array8 = np.empty(5)
print(array8)

array8 = np.empty(10)
print(array8)


In [ ]:
# RANDOM()
# array9 = np.random.rand(4)
# print(array9)

array10 = np.random.rand(2,3)
print(array10)


#### Section 3:Using np.arang()

In [ ]:
# arr1 = np.arange(21)
# print(arr1) 

# arr2 = np.arange(3,8)
# print(arr2)  

# start = 0
# stop = 16
# step = 2(if want it even)
# arr3 = np.arange(0,16,2)
# print(arr3)   

# start = 1
# stop = 21
# step = 3(if want it odd)
arr4 = np.arange(1,21,3)
print(arr4)   



### Section 4:np.linspace()

In [ ]:
#start=0
#end=10
#we asked for 5 numbers
#linspace gives us specifc number of evenly spaced values
arr5 = np.linspace(0,10,5)
print(arr5)

## Section 5:copy()

In [ ]:
arr6 = np.array([1,2,3,4])
print(arr6)   

arr7 = np.copy(arr6)
print(arr6)  
# arr7[1] = 100
# print(arr7)

## Section 6:np.identity()

In [ ]:
arr8 = np.identity(4)
print(arr8)